# theme: jekyll-theme-minimal
theme: hexo-theme-matery
language: zh-CN
url: https://darains.github.io
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

postInfo:
  date: true
  update: false
  wordCount: false # 设置文章字数统计为 true.
  totalCount: false # 设置站点文章总字数统计为 true.
  min2read: false # 阅读时长.
  readCount: false # 阅读次数.